- name: Update pip & related tools
  pip:
    name: "{{ item }}"
    state: latest
    virtualenv: "{{ virtualenv_path }}"
    virtualenv_python: "{{ openwisp2_python }}"
    virtualenv_site_packages: yes
  with_items:
    - pip
    - setuptools
    - wheel

- name: Install openwisp2 controller and its dependencies
  pip:
    name: "{{ item }}"
    state: latest
    virtualenv: "{{ virtualenv_path }}"
    virtualenv_python: "{{ openwisp2_python }}"
    virtualenv_site_packages: yes
  with_items:
    - openwisp-controller
  notify: reload supervisor

- name: Install development version of openwisp-controller
  when: openwisp2_controller_dev
  pip:
    name: https://github.com/openwisp/openwisp-controller/tarball/master
    state: latest
    virtualenv: "{{ virtualenv_path }}"
    virtualenv_python: "{{ openwisp2_python }}"
    virtualenv_site_packages: yes
  notify: reload supervisor

- name: Install development version of openwisp-users
  when: openwisp2_users_dev
  pip:
    name: https://github.com/openwisp/openwisp-users/tarball/master
    state: latest
    virtualenv: "{{ virtualenv_path }}"
    virtualenv_python: "{{ openwisp2_python }}"
    virtualenv_site_packages: yes
  notify: reload supervisor

- name: Install development version of django-netjsonconfig
  when: openwisp2_django_netjsonconfig_dev
  pip:
    name: https://github.com/openwisp/django-netjsonconfig/tarball/master
    state: latest
    virtualenv: "{{ virtualenv_path }}"
    virtualenv_python: "{{ openwisp2_python }}"
    virtualenv_site_packages: yes
  notify: reload supervisor

- name: Install development version of django-x509
  when: openwisp2_django_x509_dev
  pip:
    name: https://github.com/openwisp/django-x509/tarball/master
    state: latest
    virtualenv: "{{ virtualenv_path }}"
    virtualenv_python: "{{ openwisp2_python }}"
    virtualenv_site_packages: yes
  notify: reload supervisor

- name: Install development version of netjsonconfig
  when: openwisp2_netjsonconfig_dev
  pip:
    name: https://github.com/openwisp/netjsonconfig/tarball/master
    state: latest
    virtualenv: "{{ virtualenv_path }}"
    virtualenv_python: "{{ openwisp2_python }}"
    virtualenv_site_packages: yes
  notify: reload supervisor

- name: Install extra django apps
  pip:
    name: "{{ item }}"
    state: latest
    virtualenv: "{{ virtualenv_path }}"
    virtualenv_python: "{{ openwisp2_python }}"
    virtualenv_site_packages: yes
  with_items: "{{ openwisp2_extra_django_apps }}"
  notify: reload supervisor

- name: Install uwsgi
  pip:
    name: "{{ item }}"
    state: latest
    virtualenv: "{{ virtualenv_path }}"
    virtualenv_python: "{{ openwisp2_python }}"
    virtualenv_site_packages: yes
  with_items:
    - uwsgi
  notify: reload supervisor

- name: Install psycopg2
  when: openwisp2_database.engine in ["django.db.backends.postgresql", "django.contrib.gis.db.backends.postgis"]
  pip:
    name: psycopg2
    state: latest
    virtualenv: "{{ virtualenv_path }}"
    virtualenv_python: "{{ openwisp2_python }}"
    virtualenv_site_packages: yes
  notify: reload supervisor

- name: Install MySQL-python
  when: openwisp2_database.engine in ["django.db.backends.mysql", "django.contrib.gis.db.backends.mysql"]
  pip:
    name: MySQL-python
    state: latest
    virtualenv: "{{ virtualenv_path }}"
    virtualenv_python: "{{ openwisp2_python }}"
    virtualenv_site_packages: yes
  notify: reload supervisor

- name: Install raven (sentry client)
  when: openwisp2_sentry.get('dsn') != False
  pip:
    name: raven
    state: latest
    virtualenv: "{{ virtualenv_path }}"
    virtualenv_python: "{{ openwisp2_python }}"
    virtualenv_site_packages: yes
  notify: reload supervisor
